import { StyleSheet } from 'react-native';
import { colors, radii, spacing, textStyles, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  list: {
    gap: spacing.lg,
  },
  contextBar: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(15, 24, 31, 0.84)',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
    gap: spacing.lg,
  },
  contextHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  contextHeaderRowCompact: {
    flexDirection: 'column',
  },
  contextHeaderCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  contextBadge: {
    minHeight: 34,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(0, 215, 255, 0.2)',
    backgroundColor: 'rgba(0, 215, 255, 0.10)',
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contextBadgeCompact: {
    alignSelf: 'flex-start',
  },
  contextBarEyebrow: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  contextBadgeText: {
    ...textStyles.caption,
    color: '#B7F4FF',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  contextBarTitle: {
    ...textStyles.section,
    color: colors.text,
  },
  contextBarText: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  contextPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  contextPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  contextPillText: {
    ...textStyles.caption,
    color: colors.text,
  },
  activeSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  activeSearchChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  activeSearchCopy: {
    flex: 1,
    gap: 2,
  },
  activeSearchLabel: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  activeSearchText: {
    ...textStyles.caption,
    color: colors.text,
  },
  activeSearchClearButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.cardMuted,
    paddingHorizontal: spacing.lg,
  },
  activeSearchClearText: {
    ...textStyles.labelCaps,
    color: colors.text,
  },
  loadMoreButton: {
    minHeight: 52,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
    shadowColor: colors.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  loadMoreButtonDisabled: {
    opacity: 0.72,
  },
  loadMoreButtonText: {
    ...textStyles.button,
    color: colors.text,
    textTransform: 'uppercase',
  },
  emptyState: {
    gap: spacing.md,
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
  },
  emptyActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    paddingTop: spacing.md,
  },
  emptyActionButton: {
    minHeight: 44,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.cardMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  emptyActionButtonText: {
    ...textStyles.labelCaps,
    color: colors.text,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: typography.title,
    fontWeight: '900',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 23,
  },
});
