import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../theme/tokens';

export const customerEntryStyles = StyleSheet.create({
  sectionStack: {
    gap: spacing.lg,
  },
  heroCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlassStrong,
    padding: spacing.xl,
    gap: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
    overflow: 'hidden',
  },
  heroGlow: {
    position: 'absolute',
    top: -48,
    right: -24,
    width: 184,
    height: 184,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  heroKicker: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: colors.text,
    fontSize: typography.title,
    fontWeight: '900',
    lineHeight: 28,
  },
  heroBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  summaryStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  summaryTile: {
    minWidth: 132,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.78)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  summaryTileValue: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '900',
  },
  summaryTileLabel: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryTileBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  trustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  trustChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  trustChipWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  trustChipText: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
  },
  plannerPanel: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  plannerPanelFeatured: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  form: {
    gap: spacing.lg,
  },
  fieldGroup: {
    gap: spacing.sm,
  },
  fieldLabel: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  fieldHint: {
    color: colors.textSoft,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  fieldHintDanger: {
    color: colors.rose,
  },
  inputPremium: {
    minHeight: 50,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.78)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    color: colors.text,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    fontSize: typography.body,
  },
  helperCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.lg,
    gap: spacing.xs,
  },
  helperCardWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  helperCardSuccess: {
    borderColor: 'rgba(0, 245, 140, 0.18)',
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  helperCardDanger: {
    borderColor: 'rgba(255, 122, 122, 0.22)',
    backgroundColor: 'rgba(255, 122, 122, 0.08)',
  },
  helperTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  helperTitleSuccess: {
    color: colors.accent,
  },
  helperTitleDanger: {
    color: colors.rose,
  },
  helperBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  optInCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    padding: spacing.lg,
  },
  optInCardSelected: {
    borderColor: 'rgba(245, 200, 106, 0.24)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  optInIndicator: {
    width: 22,
    height: 22,
    marginTop: 2,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optInIndicatorSelected: {
    borderColor: colors.gold,
    backgroundColor: colors.gold,
  },
  optInTextStack: {
    flex: 1,
    gap: spacing.xs,
  },
  optInTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
  },
  optInBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  ctaPanel: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(18, 25, 31, 0.88)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  buttonFlex: {
    minWidth: 148,
    flexGrow: 1,
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: radii.lg,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  // Used to push the recovery-action button (e.g. "Sign in instead")
  // a small distance below the friendly-error message body in the
  // signup screen.
  recoveryActionSpacer: {
    marginTop: spacing.sm,
  },
  primaryButtonText: {
    color: colors.backgroundDeep,
    fontSize: typography.body,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonText: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
});
