import { StyleSheet } from 'react-native';
import { colors, radii, spacing, textStyles, typography } from '../../theme/tokens';

export const ownerPortalStyles = StyleSheet.create({
  form: {
    gap: spacing.lg,
  },
  input: {
    minHeight: 48,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    ...textStyles.body,
  },
  inputMultiline: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  wrapRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  inlineActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.sm,
  },
  inlineInput: {
    flex: 1,
  },
  inlineButton: {
    minWidth: 100,
    flexShrink: 1,
  },
  inlineButtonPrimary: {
    flex: 1,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: radii.lg,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  primaryButtonText: {
    ...textStyles.button,
    color: colors.backgroundDeep,
    letterSpacing: 0.2,
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonText: {
    ...textStyles.button,
    color: colors.text,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  helperText: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  errorText: {
    ...textStyles.body,
    color: colors.danger,
    lineHeight: 22,
  },
  successText: {
    ...textStyles.body,
    color: colors.primary,
    lineHeight: 22,
  },
  statusGrid: {
    gap: spacing.md,
  },
  list: {
    gap: spacing.md,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  metricCard: {
    minWidth: '44%',
    flexGrow: 1,
    flexShrink: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    padding: spacing.xl,
    gap: spacing.sm,
  },
  analyticsMetricCard: {
    borderRadius: radii.xl,
    padding: spacing.xxl,
    gap: spacing.lg,
    overflow: 'hidden',
  },
  metricCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  metricEyebrow: {
    flex: 1,
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.12,
  },
  metricIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  metricIconBadgeWarm: {
    backgroundColor: 'rgba(245, 200, 106, 0.12)',
    borderColor: 'rgba(245, 200, 106, 0.22)',
  },
  metricIconBadgeSuccess: {
    backgroundColor: 'rgba(0, 245, 140, 0.12)',
    borderColor: 'rgba(0, 245, 140, 0.22)',
  },
  metricIconBadgeCyan: {
    backgroundColor: 'rgba(0, 215, 255, 0.12)',
    borderColor: 'rgba(0, 215, 255, 0.22)',
  },
  metricIconBadgeRose: {
    backgroundColor: 'rgba(255, 122, 122, 0.12)',
    borderColor: 'rgba(255, 122, 122, 0.24)',
  },
  metricValueColumn: {
    gap: spacing.xs,
  },
  metricValue: {
    ...textStyles.section,
    color: colors.text,
  },
  analyticsMetricTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  metricLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  metricHelper: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  metricProgressBlock: {
    gap: spacing.xs,
  },
  metricProgressTrack: {
    height: 7,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  metricProgressFill: {
    height: '100%',
    borderRadius: radii.pill,
  },
  metricProgressFillWarm: {
    backgroundColor: '#F5C86A',
  },
  metricProgressFillSuccess: {
    backgroundColor: '#00F58C',
  },
  metricProgressFillCyan: {
    backgroundColor: '#8EDCFF',
  },
  metricProgressFillRose: {
    backgroundColor: '#FF9F92',
  },
  metricProgressLabel: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
    lineHeight: 18,
  },
  metricChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  metricChip: {
    minWidth: 88,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  metricChipValue: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  metricChipLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  metricFooter: {
    ...textStyles.caption,
    color: colors.textMuted,
    lineHeight: 18,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.md,
  },
  statusLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  statusValue: {
    ...textStyles.bodyStrong,
    color: colors.text,
    flexShrink: 1,
    textAlign: 'right',
  },
  badge: {
    alignSelf: 'flex-start',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  badgeText: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  fileCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.lg,
    gap: spacing.md,
  },
  fileName: {
    color: colors.text,
    fontSize: typography.body,
    lineHeight: 22,
  },
  choiceChip: {
    minHeight: 40,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.cardMuted,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceChipSelected: {
    backgroundColor: colors.gold,
    borderColor: colors.gold,
  },
  choiceChipText: {
    ...textStyles.caption,
    color: colors.text,
  },
  choiceChipTextSelected: {
    color: colors.backgroundDeep,
  },
  resultCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    padding: spacing.lg,
    gap: spacing.md,
  },
  resultCardSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(55, 184, 120, 0.08)',
  },
  resultBody: {
    gap: spacing.xs,
  },
  resultTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  resultMeta: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  resultWarning: {
    borderColor: 'rgba(255,122,122,0.28)',
    backgroundColor: 'rgba(255,122,122,0.08)',
  },
  resultSuccess: {
    borderColor: 'rgba(0,245,140,0.28)',
    backgroundColor: 'rgba(0,245,140,0.08)',
  },
  liveBadgeChip: {
    maxWidth: '100%',
    minHeight: 40,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.cardMuted,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveBadgeChipActive: {
    backgroundColor: 'rgba(255,122,122,0.12)',
    borderColor: 'rgba(255,122,122,0.3)',
  },
  liveBadgeChipText: {
    color: '#FFC0C0',
    ...textStyles.caption,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.border,
  },
  textArea: {
    minHeight: 110,
    textAlignVertical: 'top',
  },
  portalHeroCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlassStrong,
    padding: spacing.xxl,
    gap: spacing.xl,
    shadowColor: colors.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    overflow: 'hidden',
  },
  portalHeroGlow: {
    position: 'absolute',
    top: -52,
    right: -30,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  portalHeroKicker: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  portalHeroTitle: {
    ...textStyles.title,
    color: colors.text,
    lineHeight: 34,
  },
  portalHeroBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 24,
  },
  portalHeroMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  portalHeroMetricCard: {
    minWidth: 120,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.74)',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  portalHeroMetricValue: {
    ...textStyles.title,
    color: colors.text,
  },
  portalHeroMetricLabel: {
    ...textStyles.caption,
    color: colors.textMuted,
    letterSpacing: 0.2,
  },
  portalHeroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  surfaceSwitcher: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  surfaceSwitcherButton: {
    minWidth: 136,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  surfaceSwitcherButtonActive: {
    borderColor: 'rgba(245, 200, 106, 0.24)',
    backgroundColor: 'rgba(245, 200, 106, 0.10)',
  },
  surfaceSwitcherButtonLabel: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  surfaceSwitcherButtonLabelActive: {
    color: colors.goldSoft,
  },
  surfaceSwitcherButtonBody: {
    ...textStyles.caption,
    color: colors.textMuted,
    lineHeight: 18,
  },
  surfaceSwitcherButtonBodyActive: {
    color: colors.textSoft,
  },
  metaChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  metaChipText: {
    ...textStyles.caption,
    color: colors.textMuted,
  },
  statusPanel: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.lg,
    gap: spacing.md,
  },
  statusPanelWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  statusPanelSuccess: {
    borderColor: 'rgba(0, 245, 140, 0.18)',
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  statusPanelDanger: {
    borderColor: 'rgba(244, 62, 62, 0.18)',
    backgroundColor: 'rgba(244, 62, 62, 0.08)',
  },
  splitHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  splitHeaderCopy: {
    flex: 1,
    flexShrink: 1,
    gap: spacing.xs,
  },
  splitHeaderTitle: {
    ...textStyles.section,
    color: colors.text,
  },
  splitHeaderBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  sectionEyebrow: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  actionGrid: {
    gap: spacing.md,
  },
  actionTile: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  actionTileWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
  },
  actionTileTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  actionTileBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  actionTileMeta: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  fieldGroup: {
    gap: spacing.sm,
  },
  fieldLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.12,
  },
  fieldHint: {
    ...textStyles.body,
    color: colors.textSoft,
    lineHeight: 20,
  },
  inputPremium: {
    minHeight: 50,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    color: colors.text,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    ...textStyles.body,
  },
  textAreaPremium: {
    minHeight: 116,
    textAlignVertical: 'top',
  },
  toolbarRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  metricCardWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  metricCardSuccess: {
    borderColor: 'rgba(0, 245, 140, 0.18)',
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  metricCardCyan: {
    borderColor: 'rgba(0, 215, 255, 0.18)',
    backgroundColor: 'rgba(0, 215, 255, 0.08)',
  },
  metricCardRose: {
    borderColor: 'rgba(255, 122, 122, 0.18)',
    backgroundColor: 'rgba(255, 122, 122, 0.08)',
  },
  cardStack: {
    gap: spacing.lg,
  },
  detailTileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  detailTile: {
    minWidth: '47%',
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.lg,
    gap: spacing.xs,
  },
  detailTileLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.12,
  },
  detailTileValue: {
    ...textStyles.section,
    color: colors.text,
  },
  detailTileBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  ownerProfileSpotlight: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.07)',
    padding: spacing.xl,
    gap: spacing.lg,
    overflow: 'hidden',
  },
  ownerProfileGlow: {
    position: 'absolute',
    top: -52,
    right: -28,
    width: 168,
    height: 168,
    borderRadius: 84,
    backgroundColor: 'rgba(245, 200, 106, 0.10)',
  },
  ownerProfileTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  ownerProfileIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  ownerProfileMonogram: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 14, 19, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.22)',
  },
  ownerProfileMonogramText: {
    color: colors.goldSoft,
    ...textStyles.section,
  },
  ownerProfileIdentityCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  ownerProfileKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  ownerProfileLiveChip: {
    minHeight: 32,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ownerProfileLiveChipText: {
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  ownerProfileTitle: {
    ...textStyles.title,
    color: colors.text,
    lineHeight: 30,
  },
  ownerProfileMeta: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  ownerProfileStatusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  ownerProfileStatusCard: {
    minWidth: 120,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(8, 14, 19, 0.58)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  ownerProfileStatusValue: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  ownerProfileStatusLabel: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  ownerProfileStatusBody: {
    ...textStyles.caption,
    color: colors.textMuted,
    lineHeight: 18,
  },
  reviewComposerCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.lg,
    gap: spacing.md,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  tag: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  tagText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    fontWeight: '800',
  },
  planGrid: {
    gap: spacing.lg,
  },
  planTile: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    padding: spacing.xl,
    gap: spacing.md,
  },
  planTileFeatured: {
    borderColor: 'rgba(245, 200, 106, 0.24)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  planPrice: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '900',
  },
  planPriceCaption: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  planFeatureList: {
    gap: spacing.sm,
  },
  planFeatureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  planFeatureText: {
    flex: 1,
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 20,
  },
  planFeatureTextLocked: {
    color: '#666',
  },
  billingCycleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 4,
  },
  billingCycleTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  billingCycleTabActive: {
    backgroundColor: 'rgba(46,204,113,0.15)',
  },
  billingCycleTabInactive: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  billingCycleTabTextActive: {
    color: '#2ECC71',
    fontWeight: '700',
    fontSize: 14,
  },
  billingCycleTabTextInactive: {
    color: '#C4B8B0',
    fontWeight: '700',
    fontSize: 14,
  },
  planTileCurrentTier: {
    borderColor: '#2ECC71',
    borderWidth: 2,
  },
  planPriceCaptionSmall: {
    fontSize: 12,
  },
  buttonCurrentTier: {
    backgroundColor: 'rgba(46,204,113,0.2)',
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  valueCallout: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sectionStack: {
    gap: spacing.xl,
  },
  plannerPanel: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  plannerPanelFeatured: {
    borderColor: 'rgba(245, 200, 106, 0.22)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  plannerPanelSuccess: {
    borderColor: 'rgba(0, 245, 140, 0.18)',
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  analyticsSectionCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.68)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  analyticsSectionHeader: {
    gap: spacing.xs,
  },
  analyticsSectionEyebrow: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  analyticsSectionTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  analyticsSectionBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  analyticsSpotlightCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.24)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  analyticsSpotlightHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  analyticsSpotlightValue: {
    color: colors.text,
    fontSize: 30,
    fontWeight: '900',
  },
  analyticsSpotlightBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  analyticsInlineStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  analyticsInlineStat: {
    minWidth: 92,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(8, 14, 19, 0.34)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  analyticsInlineStatLabel: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  analyticsInlineStatValue: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  summaryStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  summaryTile: {
    minWidth: 100,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '40%',
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  summaryTileValue: {
    color: colors.text,
    ...textStyles.title,
    lineHeight: 30,
  },
  summaryTileLabel: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  summaryTileBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  emptyStateCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.66)',
    padding: spacing.xl,
    gap: spacing.sm,
  },
  emptyStateTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  emptyStateBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  ctaPanel: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(18, 25, 31, 0.88)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  analyticsScrollFrame: {
    marginHorizontal: -spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  onboardingStepRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  onboardingStepChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  onboardingStepChipActive: {
    borderColor: 'rgba(245, 200, 106, 0.24)',
    backgroundColor: 'rgba(245, 200, 106, 0.10)',
  },
  onboardingStepChipText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  onboardingStepChipTextActive: {
    color: colors.goldSoft,
  },
  onboardingFileCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    padding: spacing.lg,
    gap: spacing.md,
  },
  onboardingFileHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  onboardingFileMeta: {
    flex: 1,
    gap: spacing.xs,
  },
  onboardingFileHint: {
    color: colors.textSoft,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  onboardingInfoCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    padding: spacing.lg,
    gap: spacing.sm,
  },
  onboardingInfoCardWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  onboardingInfoCardSuccess: {
    borderColor: 'rgba(0, 245, 140, 0.18)',
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  stageList: {
    gap: spacing.md,
  },
  stageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  stageIconWrap: {
    width: 28,
    alignItems: 'center',
    paddingTop: 2,
  },
  stageCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  stageLabel: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  stageBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  stageBadge: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  stageBadgeText: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  uploadButton: {
    minHeight: 50,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 140, 0.28)',
    backgroundColor: 'rgba(0, 245, 140, 0.10)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row' as const,
    gap: spacing.sm,
  },
  uploadButtonText: {
    ...textStyles.button,
    color: colors.primary,
    letterSpacing: 0.2,
  },
  uploadPreview: {
    width: 80,
    height: 80,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
    marginTop: spacing.sm,
  },
  limitNotice: {
    ...textStyles.body,
    color: colors.warning,
    textAlign: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  promotionActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  promotionActionFlex: {
    flex: 1,
  },
  promotionDeleteButton: {
    flex: 0,
    paddingHorizontal: 16,
    borderColor: '#FF6B6B',
  },
  promotionDeleteText: {
    color: '#FF6B6B',
  },
});
