import {
  OwnerDispensaryClaimDocument,
  OwnerPortalAccessState,
  OwnerProfileDocument,
  OwnerPortalWorkspaceDocument,
  OwnerStorefrontProfileToolsDocument,
  OwnerStorefrontPromotionDocument,
} from '../../types/ownerPortal';
import { StorefrontSummary } from '../../types/storefront';

export const OWNER_PORTAL_PREVIEW_UID = 'owner-preview';

export const ownerPortalPreviewAccessState: OwnerPortalAccessState = {
  enabled: true,
  restricted: false,
  allowlisted: true,
};

export const ownerPortalPreviewStorefront: StorefrontSummary = {
  id: 'canopy-trove-preview-store',
  licenseId: 'OCM-CAURD-2048',
  marketId: 'nyc',
  displayName: 'Canopy Trove Garden Flatiron',
  legalName: 'Canopy Trove Garden LLC',
  addressLine1: '145 W 23rd St',
  city: 'New York',
  state: 'NY',
  zip: '10011',
  coordinates: {
    latitude: 40.7423,
    longitude: -73.9936,
  },
  distanceMiles: 1.4,
  travelMinutes: 6,
  rating: 4.7,
  reviewCount: 28,
  openNow: true,
  isVerified: true,
  mapPreviewLabel: '1.4 mi route preview',
  promotionText: 'Preview deal: 15% off premium flower',
  activePromotionId: 'owner-preview-promo-live',
  promotionPlacementSurfaces: ['nearby', 'browse', 'hot_deals'],
  promotionPlacementScope: 'storefront_area',
  thumbnailUrl: null,
};

export const ownerPortalPreviewSearchResults: StorefrontSummary[] = [
  ownerPortalPreviewStorefront,
  {
    ...ownerPortalPreviewStorefront,
    id: 'canopy-trove-preview-store-2',
    licenseId: 'OCM-CAURD-3050',
    displayName: 'Canopy Trove Uptown Reserve',
    legalName: 'Canopy Trove Uptown Reserve LLC',
    addressLine1: '812 Amsterdam Ave',
    city: 'New York',
    zip: '10025',
    distanceMiles: 4.8,
    travelMinutes: 16,
    mapPreviewLabel: '4.8 mi route preview',
    promotionText: 'Preview deal: Free pre-roll with cart purchase',
  },
  {
    ...ownerPortalPreviewStorefront,
    id: 'canopy-trove-preview-store-3',
    licenseId: 'OCM-CAURD-4112',
    displayName: 'Canopy Trove Brooklyn House',
    legalName: 'Canopy Trove Brooklyn House LLC',
    addressLine1: '288 Flatbush Ave',
    city: 'Brooklyn',
    zip: '11217',
    distanceMiles: 6.2,
    travelMinutes: 21,
    mapPreviewLabel: '6.2 mi route preview',
    promotionText: 'Preview deal: Buy 2 gummies, get 1 free',
  },
];

export const ownerPortalPreviewProfile: OwnerProfileDocument = {
  uid: OWNER_PORTAL_PREVIEW_UID,
  legalName: 'Alex Rivera',
  phone: '(212) 555-0188',
  companyName: 'Canopy Trove Garden LLC',
  identityVerificationStatus: 'pending',
  businessVerificationStatus: 'verified',
  dispensaryId: ownerPortalPreviewStorefront.id,
  onboardingStep: 'subscription',
  subscriptionStatus: 'inactive',
  badgeLevel: 2,
  earnedBadgeIds: ['verified_business', 'top_photos'],
  selectedBadgeIds: ['verified_business'],
  createdAt: '2026-03-20T14:15:00.000Z',
  updatedAt: '2026-03-28T13:40:00.000Z',
};

export const ownerPortalPreviewClaim: OwnerDispensaryClaimDocument = {
  ownerUid: OWNER_PORTAL_PREVIEW_UID,
  dispensaryId: ownerPortalPreviewStorefront.id,
  claimStatus: 'approved',
  submittedAt: '2026-03-22T15:00:00.000Z',
  reviewedAt: '2026-03-23T11:30:00.000Z',
  reviewNotes: 'Preview claim approved for design review.',
};

export const ownerPortalPreviewProfileTools: OwnerStorefrontProfileToolsDocument = {
  storefrontId: ownerPortalPreviewStorefront.id,
  ownerUid: OWNER_PORTAL_PREVIEW_UID,
  menuUrl: 'https://canopytrove.com/demo-menu',
  featuredPhotoUrls: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=80',
    'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=900&q=80',
  ],
  cardPhotoUrl:
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
  verifiedBadgeLabel: 'Verified Owner',
  featuredBadges: ['Fast pickup', 'Fresh drops', 'Owner picks'],
  cardSummary: 'Owner-curated flower drops, fast pickup, and rotating premium bundles.',
  updatedAt: '2026-03-28T13:40:00.000Z',
};

export const ownerPortalPreviewPromotions: OwnerStorefrontPromotionDocument[] = [
  {
    id: 'owner-preview-promo-live',
    storefrontId: ownerPortalPreviewStorefront.id,
    ownerUid: OWNER_PORTAL_PREVIEW_UID,
    title: '20% off premium flower',
    description: '20% off premium flower through Sunday evening.',
    badges: ['20% Off', 'Hot Deal', 'Weekend Drop'],
    startsAt: '2026-03-28T09:00:00.000Z',
    endsAt: '2026-03-30T02:00:00.000Z',
    status: 'active',
    audience: 'all_followers',
    alertFollowersOnStart: true,
    cardTone: 'hot_deal',
    placementSurfaces: ['nearby', 'browse', 'hot_deals'],
    placementScope: 'storefront_area',
    createdAt: '2026-03-28T09:00:00.000Z',
    updatedAt: '2026-03-28T09:00:00.000Z',
  },
  {
    id: 'owner-preview-promo-next',
    storefrontId: ownerPortalPreviewStorefront.id,
    ownerUid: OWNER_PORTAL_PREVIEW_UID,
    title: 'Loyalty edible bundle',
    description: 'Bundle pricing for saved followers next week.',
    badges: ['Bundle', 'Next Week'],
    startsAt: '2026-04-02T15:00:00.000Z',
    endsAt: '2026-04-06T03:00:00.000Z',
    status: 'scheduled',
    audience: 'frequent_visitors',
    alertFollowersOnStart: true,
    cardTone: 'owner_featured',
    placementSurfaces: ['browse', 'hot_deals'],
    placementScope: 'statewide',
    createdAt: '2026-03-28T11:00:00.000Z',
    updatedAt: '2026-03-28T11:00:00.000Z',
  },
];

export const ownerPortalPreviewWorkspace: OwnerPortalWorkspaceDocument = {
  ownerProfile: ownerPortalPreviewProfile,
  ownerClaim: ownerPortalPreviewClaim,
  storefrontSummary: {
    id: ownerPortalPreviewStorefront.id,
    displayName: ownerPortalPreviewStorefront.displayName,
    addressLine1: ownerPortalPreviewStorefront.addressLine1,
    city: ownerPortalPreviewStorefront.city,
    state: ownerPortalPreviewStorefront.state,
    zip: ownerPortalPreviewStorefront.zip,
    promotionText: ownerPortalPreviewStorefront.promotionText,
    promotionBadges: ['20% Off', 'Hot Deal', 'Weekend Drop'],
  },
  metrics: {
    followerCount: 118,
    storefrontImpressions7d: 1840,
    storefrontOpenCount7d: 436,
    routeStarts7d: 129,
    websiteTapCount7d: 74,
    phoneTapCount7d: 31,
    menuTapCount7d: 92,
    reviewCount30d: 16,
    openReportCount: 1,
    averageRating: 4.7,
    replyRate: 0.75,
    openToRouteRate: 29.6,
    openToWebsiteRate: 17,
    openToPhoneRate: 7.1,
    openToMenuRate: 21.1,
  },
  patternFlags: [
    {
      id: 'followers-waiting',
      title: 'Followers react fast to new deals',
      body: 'Saved followers convert best when the deal launches within the same day.',
      tone: 'success',
    },
    {
      id: 'report-open',
      title: 'One report needs review',
      body: 'Check the report inbox and respond to the flagged listing issue quickly.',
      tone: 'warning',
    },
  ],
  recentReviews: [
    {
      id: 'owner-preview-review-1',
      storefrontId: ownerPortalPreviewStorefront.id,
      authorName: 'Avery',
      authorProfileId: 'preview-reviewer-1',
      rating: 5,
      relativeTime: '2 hr ago',
      text: 'Fast pickup, clean space, and great staff recommendations.',
      tags: ['Fast pickup', 'Friendly staff'],
      helpfulCount: 4,
      ownerReply: {
        ownerUid: OWNER_PORTAL_PREVIEW_UID,
        ownerDisplayName: ownerPortalPreviewProfile.companyName,
        text: "Appreciate you. We just added a fresh-drop badge to today's menu.",
        respondedAt: '2026-03-28T13:50:00.000Z',
      },
      isLowRating: false,
    },
    {
      id: 'owner-preview-review-2',
      storefrontId: ownerPortalPreviewStorefront.id,
      authorName: 'Jordan',
      authorProfileId: 'preview-reviewer-2',
      rating: 2,
      relativeTime: '1 day ago',
      text: 'The line moved slower than expected.',
      tags: ['Wait time'],
      helpfulCount: 1,
      ownerReply: null,
      isLowRating: true,
    },
  ],
  recentReports: [
    {
      id: 'owner-preview-report-1',
      storefrontId: ownerPortalPreviewStorefront.id,
      authorName: 'Canopy Trove user',
      profileId: 'preview-report-profile',
      reason: 'Hours',
      description: 'Weekend closing time looked outdated.',
      createdAt: '2026-03-28T10:20:00.000Z',
      moderationStatus: 'open',
      reviewedAt: null,
      reviewNotes: null,
    },
  ],
  promotions: ownerPortalPreviewPromotions,
  promotionPerformance: [
    {
      promotionId: 'owner-preview-promo-live',
      title: '20% off premium flower',
      status: 'active',
      badges: ['20% Off', 'Hot Deal', 'Weekend Drop'],
      startsAt: '2026-03-28T09:00:00.000Z',
      endsAt: '2026-03-30T02:00:00.000Z',
      metrics: {
        impressions: 620,
        opens: 190,
        saves: 42,
        redeemStarts: 68,
        redeemed: 21,
        websiteTaps: 23,
        phoneTaps: 7,
        menuTaps: 35,
        clickThroughRate: 30.6,
        actionRate: 21.3,
      },
    },
    {
      promotionId: 'owner-preview-promo-next',
      title: 'Loyalty edible bundle',
      status: 'scheduled',
      badges: ['Bundle', 'Next Week'],
      startsAt: '2026-04-02T15:00:00.000Z',
      endsAt: '2026-04-06T03:00:00.000Z',
      metrics: {
        impressions: 0,
        opens: 0,
        saves: 0,
        redeemStarts: 0,
        redeemed: 0,
        websiteTaps: 0,
        phoneTaps: 0,
        menuTaps: 0,
        clickThroughRate: 0,
        actionRate: 0,
      },
    },
  ],
  profileTools: ownerPortalPreviewProfileTools,
  ownerAlertStatus: {
    pushEnabled: true,
    updatedAt: '2026-03-28T13:42:00.000Z',
  },
};

