import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  summaryStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  summaryTile: {
    minWidth: 132,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  summaryTileValue: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '900',
  },
  summaryTileLabel: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryTileBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  ratingRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  ratingButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  ratingButtonActive: {
    borderColor: 'rgba(245, 200, 106, 0.28)',
    backgroundColor: 'rgba(245, 200, 106, 0.12)',
  },
  input: {
    minHeight: 148,
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    color: colors.text,
    padding: spacing.lg,
    fontSize: typography.body,
    lineHeight: 22,
  },
  caption: {
    marginTop: spacing.sm,
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  helperText: {
    marginTop: spacing.sm,
    color: colors.textSoft,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  validationText: {
    marginTop: spacing.sm,
    color: colors.warning,
    fontSize: typography.caption,
    fontWeight: '700',
    lineHeight: 18,
  },
  errorText: {
    marginBottom: spacing.sm,
    color: colors.danger,
    fontSize: typography.caption,
    fontWeight: '800',
    lineHeight: 18,
  },
  emojiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  emojiChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  emojiChipText: {
    fontSize: 20,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  tagChip: {
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  tagChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  tagChipText: {
    color: colors.text,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  tagChipTextSelected: {
    color: colors.background,
  },
  urlInput: {
    minHeight: 48,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    color: colors.text,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: typography.body,
  },
  gifPreview: {
    marginTop: spacing.md,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
    width: '100%',
    aspectRatio: 1.2,
  },
  gifPickerActions: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.md,
    flexWrap: 'wrap',
  },
  gifPickerButton: {
    minHeight: 50,
    flex: 1,
    minWidth: 160,
    borderRadius: radii.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    shadowColor: colors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  gifPickerButtonText: {
    color: colors.background,
    fontSize: typography.body,
    fontWeight: '800',
  },
  gifPickerClearButton: {
    minHeight: 50,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  gifPickerClearButtonText: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
  },
  attributionText: {
    marginTop: spacing.sm,
    color: colors.textSoft,
    fontSize: typography.caption,
  },
  ctaPanel: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(18, 25, 31, 0.88)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  submitButton: {
    minHeight: 52,
    borderRadius: radii.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    shadowColor: colors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  submitButtonDisabled: {
    opacity: 0.45,
  },
  submitButtonText: {
    color: colors.background,
    fontSize: typography.body,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
});
