import { StyleSheet } from 'react-native';
import { colors, fontFamilies, radii, spacing, textStyles } from '../../theme/tokens';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: 'transparent',
    borderRadius: radii.xl,
    gap: 0,
  },
  cardCompact: {
    gap: 0,
  },
  cardPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.988 }],
  },
  previewWrap: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: 0,
    zIndex: 1,
    shadowColor: colors.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  body: {
    marginTop: -spacing.xl,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
    paddingTop: spacing.xl + spacing.sm,
    gap: spacing.md,
    backgroundColor: colors.surfaceGlassStrong,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    shadowColor: colors.shadow,
    shadowOpacity: 0.26,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  bodyHotDeal: {
    backgroundColor: 'rgba(33, 16, 17, 0.96)',
    borderColor: 'rgba(255,122,122,0.22)',
  },
  bodyOwnerFeatured: {
    backgroundColor: 'rgba(18, 34, 29, 0.96)',
    borderColor: 'rgba(0,245,140,0.22)',
  },
  bodySaved: {
    backgroundColor: 'rgba(15, 27, 21, 0.96)',
    borderColor: 'rgba(0,245,140,0.18)',
  },
  bodyVisited: {
    backgroundColor: 'rgba(14, 23, 36, 0.96)',
    borderColor: 'rgba(77,156,255,0.18)',
  },
  bodyNewToYou: {
    backgroundColor: 'rgba(36, 28, 14, 0.96)',
    borderColor: 'rgba(247,199,101,0.20)',
  },
  kickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  kickerChip: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
  },
  kickerChipDefault: {
    backgroundColor: 'rgba(245, 200, 106, 0.10)',
    borderColor: 'rgba(245, 200, 106, 0.20)',
  },
  kickerChipHotDeal: {
    backgroundColor: 'rgba(255, 122, 122, 0.12)',
    borderColor: 'rgba(255, 122, 122, 0.24)',
  },
  kickerChipOwnerFeatured: {
    backgroundColor: 'rgba(0, 245, 140, 0.10)',
    borderColor: 'rgba(0, 245, 140, 0.22)',
  },
  kickerChipSaved: {
    backgroundColor: 'rgba(0, 245, 140, 0.09)',
    borderColor: 'rgba(0, 245, 140, 0.18)',
  },
  kickerChipVisited: {
    backgroundColor: 'rgba(77, 156, 255, 0.12)',
    borderColor: 'rgba(77, 156, 255, 0.24)',
  },
  kickerChipNewToYou: {
    backgroundColor: 'rgba(245, 200, 106, 0.12)',
    borderColor: 'rgba(245, 200, 106, 0.24)',
  },
  kickerChipText: {
    ...textStyles.labelCaps,
    color: colors.goldSoft,
    letterSpacing: 0.5,
  },
  kickerChipTextHotDeal: {
    color: '#FFC9C0',
  },
  kickerChipTextOwnerFeatured: {
    color: colors.primary,
  },
  kickerChipTextSaved: {
    color: '#8FF2C3',
  },
  kickerChipTextVisited: {
    color: colors.blue,
  },
  kickerChipTextNewToYou: {
    color: colors.warning,
  },
  kickerMetric: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  kickerMetricText: {
    ...textStyles.caption,
    fontFamily: fontFamilies.bodyBold,
    color: colors.textSoft,
  },
  ownerHeadlineChip: {
    maxWidth: 150,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(0,245,140,0.22)',
    backgroundColor: 'rgba(0,245,140,0.08)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  ownerHeadlineText: {
    ...textStyles.labelCaps,
    color: colors.primary,
  },
  ownerSummaryText: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  ownerBadgeWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  ownerBadge: {
    maxWidth: '100%',
    borderRadius: radii.pill,
    backgroundColor: 'rgba(0,245,140,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0,245,140,0.24)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  ownerBadgeText: {
    ...textStyles.labelCaps,
    color: colors.primary,
  },
  promotionBadgeWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  promotionBadge: {
    maxWidth: '100%',
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255,122,122,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,122,122,0.28)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  promotionBadgeText: {
    ...textStyles.labelCaps,
    color: '#FFC0C0',
  },
  promotionBadgeExpiry: {
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  promotionBadgeExpiryText: {
    ...textStyles.caption,
    fontFamily: fontFamilies.bodyBold,
    color: colors.textSoft,
  },
  badgeRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: -2,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  statusOpen: {
    borderColor: 'rgba(0,245,140,0.28)',
    backgroundColor: 'rgba(0,245,140,0.08)',
  },
  statusClosed: {
    borderColor: 'rgba(255,122,122,0.28)',
    backgroundColor: 'rgba(255,122,122,0.08)',
  },
  statusVerified: {
    borderColor: 'rgba(0,245,140,0.28)',
    backgroundColor: 'rgba(0,245,140,0.08)',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  statusDotOpen: {
    backgroundColor: colors.primary,
  },
  statusDotClosed: {
    backgroundColor: colors.danger,
  },
  statusText: {
    ...textStyles.labelCaps,
    color: colors.text,
  },
  title: {
    flex: 1,
    fontFamily: fontFamilies.display,
    color: colors.text,
    fontSize: 21,
    lineHeight: 26,
    letterSpacing: -0.2,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  metaRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: 'rgba(8, 14, 19, 0.78)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  metaChipText: {
    ...textStyles.caption,
    fontFamily: fontFamilies.bodyBold,
    color: colors.accent,
  },
  ratingHelperText: {
    ...textStyles.caption,
    fontFamily: fontFamilies.bodyMedium,
    color: colors.textSoft,
    lineHeight: 18,
  },
  promotionBanner: {
    minHeight: 46,
    borderRadius: radii.lg,
    backgroundColor: colors.danger,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: colors.danger,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  promotionText: {
    flex: 1,
    ...textStyles.bodyStrong,
    color: colors.background,
    lineHeight: 20,
  },
  promotionTeaserBanner: {
    minHeight: 46,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.82)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  promotionTeaserText: {
    flex: 1,
    ...textStyles.bodyStrong,
    color: colors.text,
    lineHeight: 20,
  },
  primaryCta: {
    minHeight: 48,
    borderRadius: radii.lg,
    backgroundColor: colors.gold,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    shadowColor: colors.gold,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
  },
  primaryCtaSplit: {
    flex: 1,
  },
  primaryCtaText: {
    ...textStyles.button,
    color: colors.backgroundDeep,
    letterSpacing: 0.2,
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  secondaryCta: {
    flex: 1,
    minHeight: 48,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.80)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 5 },
  },
  secondaryCtaText: {
    ...textStyles.button,
    color: colors.text,
    letterSpacing: 0.4,
  },
});
