import { StyleSheet } from 'react-native';
import { colors, radii, spacing, textStyles, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  list: {
    gap: spacing.lg,
  },
  locationStateBar: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.74)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: 2,
  },
  locationStateLabel: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  locationStateValue: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  locationPanel: {
    gap: spacing.md,
    padding: spacing.xl,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(15, 24, 31, 0.86)',
    shadowColor: colors.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  locationPanelBadge: {
    minHeight: 34,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 140, 0.18)',
    backgroundColor: 'rgba(0, 245, 140, 0.10)',
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationPanelBadgeText: {
    ...textStyles.caption,
    color: colors.accent,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  locationPanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  locationPanelHeaderCompact: {
    flexDirection: 'column',
  },
  locationPanelHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  locationPanelHeaderActionsCompact: {
    width: '100%',
    justifyContent: 'space-between',
  },
  locationPanelTitleWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  locationPanelTitle: {
    ...textStyles.section,
    color: colors.text,
  },
  locationPanelSubtitle: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  closeButton: {
    minHeight: 40,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  closeButtonText: {
    ...textStyles.labelCaps,
    color: colors.text,
  },
  locationActionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  locationActionRowCompact: {
    flexDirection: 'column',
  },
  emptyState: {
    gap: spacing.sm,
    paddingVertical: spacing.xl,
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingTop: spacing.md,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '800',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  errorText: {
    color: colors.warning,
    fontSize: typography.caption,
    lineHeight: 18,
    paddingTop: spacing.xs,
  },
  infoBanner: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  infoBannerText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
    fontWeight: '700',
  },
  primaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: radii.md,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    shadowColor: colors.gold,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  fullWidthButton: {
    flex: 0,
    width: '100%',
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  primaryButtonText: {
    ...textStyles.button,
    color: colors.backgroundDeep,
    textTransform: 'uppercase',
  },
  secondaryButtonText: {
    ...textStyles.button,
    color: colors.text,
    textTransform: 'uppercase',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
});
