import { StyleSheet } from 'react-native';
import { colors, radii, spacing, textStyles, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  content: {
    padding: spacing.xl,
    paddingBottom: spacing.xxl,
    gap: spacing.lg,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.md,
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    shadowColor: colors.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  headerBadgeText: {
    ...textStyles.caption,
    color: colors.text,
    letterSpacing: 0.12,
  },
  hero: {
    position: 'relative',
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlassStrong,
    padding: spacing.xxl,
    gap: spacing.xl,
    shadowColor: colors.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
    overflow: 'hidden',
  },
  heroTone: {
    position: 'absolute',
    top: -52,
    right: -24,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  heroKicker: {
    ...textStyles.labelCaps,
    color: colors.goldSoft,
    letterSpacing: 0.95,
  },
  title: {
    ...textStyles.display,
    color: colors.text,
    fontSize: 29,
    lineHeight: 34,
  },
  address: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  heroSummaryStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  heroSummaryTile: {
    minWidth: 132,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.68)',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  heroSummaryValue: {
    ...textStyles.title,
    color: colors.text,
  },
  heroSummaryLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.12,
  },
  heroSummaryBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  metaRow: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.66)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  metaText: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  ratingHelperText: {
    ...textStyles.body,
    color: colors.textSoft,
    lineHeight: 20,
  },
  ownerBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  ownerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(0,245,140,0.18)',
    backgroundColor: 'rgba(0,245,140,0.08)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  ownerBadgeText: {
    ...textStyles.caption,
    color: colors.primary,
  },
  ownerSummaryText: {
    ...textStyles.body,
    color: colors.textSoft,
    lineHeight: 22,
  },
  ctaRow: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  primaryButton: {
    flex: 1,
    minWidth: 140,
    minHeight: 52,
    borderRadius: radii.lg,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
    shadowColor: colors.gold,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  primaryButtonText: {
    ...textStyles.button,
    color: colors.backgroundDeep,
  },
  secondaryButton: {
    flex: 1,
    minWidth: 140,
    minHeight: 52,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  secondaryButtonText: {
    ...textStyles.button,
    color: colors.text,
  },
  secondaryCtaRow: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  tertiaryButton: {
    flex: 1,
    minWidth: 140,
    minHeight: 52,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  tertiaryButtonText: {
    ...textStyles.caption,
    color: colors.text,
    letterSpacing: 0.12,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  loadingInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: typography.body,
  },
  operationalList: {
    gap: spacing.md,
  },
  operationalRow: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  operationalRowMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  operationalIconWrap: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    alignItems: 'center',
    justifyContent: 'center',
  },
  operationalIconWrapActive: {
    borderColor: colors.borderStrong,
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  operationalIconWrapChecking: {
    borderColor: 'rgba(247, 199, 101, 0.32)',
    backgroundColor: 'rgba(247, 199, 101, 0.10)',
  },
  operationalCopy: {
    flex: 1,
    gap: 3,
  },
  operationalLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.12,
  },
  operationalValue: {
    ...textStyles.bodyStrong,
    color: colors.text,
    lineHeight: 21,
  },
  operationalValueMuted: {
    color: colors.textMuted,
    fontWeight: '600',
  },
  operationalStatusPill: {
    alignSelf: 'flex-start',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderWidth: 1,
  },
  operationalStatusAvailable: {
    borderColor: colors.borderStrong,
    backgroundColor: 'rgba(0, 245, 140, 0.12)',
  },
  operationalStatusChecking: {
    borderColor: 'rgba(247, 199, 101, 0.28)',
    backgroundColor: 'rgba(247, 199, 101, 0.12)',
  },
  operationalStatusUnavailable: {
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
  },
  operationalStatusText: {
    ...textStyles.caption,
    letterSpacing: 0.12,
  },
  operationalStatusTextAvailable: {
    color: colors.primary,
  },
  operationalStatusTextChecking: {
    color: colors.warning,
  },
  operationalStatusTextUnavailable: {
    color: colors.textSoft,
  },
  infoNoticeCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  infoNoticeCardWarm: {
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  infoNoticeCardCyan: {
    borderColor: 'rgba(0, 215, 255, 0.18)',
    backgroundColor: 'rgba(0, 215, 255, 0.08)',
  },
  infoNoticeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  infoNoticeIconWrap: {
    width: 38,
    height: 38,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoNoticeCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  infoNoticeTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  infoNoticeBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  amenityWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  amenityChip: {
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceGlass,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  amenityText: {
    ...textStyles.caption,
    color: colors.accent,
  },
  listBlock: {
    gap: spacing.md,
  },
  hoursCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  hoursDay: {
    ...textStyles.caption,
    color: colors.goldSoft,
    letterSpacing: 0.12,
    flex: 1,
  },
  hoursValue: {
    ...textStyles.bodyStrong,
    color: colors.text,
    lineHeight: 21,
    textAlign: 'right',
  },
  hoursValueMuted: {
    color: colors.textMuted,
    fontWeight: '600',
  },
  liveDealsList: {
    gap: spacing.md,
  },
  liveDealCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    padding: spacing.xl,
    gap: spacing.lg,
  },
  liveDealHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  liveDealTitleWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  liveDealTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
    lineHeight: 22,
  },
  liveDealDescription: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  liveDealMetaColumn: {
    alignItems: 'flex-end',
    gap: spacing.sm,
  },
  liveDealToneChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  liveDealToneChipText: {
    ...textStyles.caption,
    color: colors.goldSoft,
    letterSpacing: 0.12,
  },
  liveDealExpiryChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  liveDealExpiryChipText: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  liveDealBadgeWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  liveDealBadge: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  liveDealBadgeText: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  listLine: {
    ...textStyles.body,
    color: colors.text,
    lineHeight: 22,
  },
  reviewList: {
    gap: spacing.md,
  },
  reviewCard: {
    backgroundColor: 'rgba(8, 14, 19, 0.80)',
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.xl,
    gap: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  reviewHeaderMain: {
    flex: 1,
    gap: 4,
  },
  reviewAuthor: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  reviewMeta: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
    lineHeight: 18,
  },
  reviewRatingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  reviewRatingText: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
  },
  reviewText: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  reviewGif: {
    width: '100%',
    aspectRatio: 1.2,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  reviewPhotoRow: {
    gap: spacing.md,
  },
  reviewPhotoCard: {
    width: 148,
    height: 148,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  reviewDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  reviewActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  reviewActionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  reviewActionMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  reviewActionMetaText: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  reviewHelpfulButton: {
    minHeight: 40,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.cyan,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  reviewHelpfulButtonDisabled: {
    opacity: 0.5,
  },
  reviewHelpfulButtonText: {
    color: colors.background,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  reviewBlockButton: {
    minHeight: 40,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewBlockButtonText: {
    color: colors.text,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  reviewReportButton: {
    minHeight: 40,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewReportButtonText: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  reviewModerationNote: {
    color: colors.textSoft,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  reviewTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  reviewTag: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  reviewTagText: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '600',
  },
  reviewOwnerReplyCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    padding: spacing.lg,
    gap: spacing.sm,
  },
  reviewOwnerReplyLabel: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  reviewOwnerReplyMeta: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  reviewOwnerReplyText: {
    color: colors.text,
    fontSize: typography.body,
    lineHeight: 21,
  },
  reviewEmptyCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceGlass,
    padding: spacing.xxl,
    gap: spacing.md,
  },
  reviewEmptyTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '900',
  },
  reviewEmptyBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  photoRow: {
    gap: spacing.md,
  },
  photoCard: {
    width: 228,
    height: 146,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  emptyText: {
    color: colors.textSoft,
    fontSize: typography.body,
    lineHeight: 22,
  },
});
