import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  shell: {
    borderRadius: radii.lg,
    borderWidth: 1.5,
    position: 'relative',
    justifyContent: 'center',
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  glowPrimary: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 245, 140, 0.12)',
    top: -90,
    right: -70,
  },
  glowSecondary: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 215, 255, 0.10)',
    bottom: -80,
    left: -60,
  },
  gridBlock: {
    position: 'absolute',
    top: 22,
    right: 18,
    width: 84,
    height: 84,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  gridBlockOffset: {
    position: 'absolute',
    bottom: 20,
    right: 54,
    width: 54,
    height: 54,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.05)',
    backgroundColor: 'rgba(255,255,255,0.015)',
  },
  labelPill: {
    position: 'absolute',
    left: spacing.md,
    top: spacing.md,
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  labelText: {
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  statusPill: {
    position: 'absolute',
    right: spacing.md,
    top: spacing.md,
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  statusText: {
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  content: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xl,
    justifyContent: 'flex-end',
  },
  copyWrap: {
    gap: spacing.xs,
    maxWidth: '82%',
  },
  headline: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '800',
  },
  supportingText: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 20,
  },
});
