import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  shell: {
    borderRadius: radii.lg,
    borderWidth: 1.5,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
  },
  imageBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(6, 10, 12, 0.34)',
  },
  glowPrimary: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 245, 140, 0.12)',
    top: -90,
    right: -70,
  },
  glowSecondary: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 215, 255, 0.10)',
    bottom: -80,
    left: -60,
  },
  gridBlock: {
    position: 'absolute',
    top: 54,
    right: 16,
    width: 76,
    height: 76,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  gridBlockOffset: {
    position: 'absolute',
    bottom: 18,
    right: 46,
    width: 54,
    height: 54,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.05)',
    backgroundColor: 'rgba(255,255,255,0.015)',
  },
  topRail: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  topRailStart: {
    flex: 1,
    alignItems: 'flex-start',
  },
  topRailEnd: {
    flex: 1,
    alignItems: 'flex-end',
  },
  labelPill: {
    minHeight: 28,
    maxWidth: '100%',
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 1,
    justifyContent: 'center',
  },
  labelText: {
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    lineHeight: 14,
  },
  statusPill: {
    minHeight: 28,
    maxWidth: '100%',
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 1,
    justifyContent: 'center',
  },
  statusText: {
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    lineHeight: 14,
  },
  content: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xl,
    justifyContent: 'flex-end',
  },
  copyWrap: {
    gap: spacing.xs,
    maxWidth: '76%',
  },
  headline: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '800',
    textShadowColor: 'rgba(0, 0, 0, 0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  supportingText: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.28)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
});
