import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  heroCard: {
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: radii.xl,
    padding: spacing.xl,
    gap: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    overflow: 'hidden',
  },
  heroGlow: {
    position: 'absolute',
    top: -40,
    right: -20,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.lg,
  },
  avatarWrap: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245, 200, 106, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.24)',
    shadowColor: colors.gold,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  avatarText: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  heroBody: {
    flex: 1,
    gap: spacing.sm,
  },
  heroTitleRow: {
    gap: spacing.sm,
  },
  heroName: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 30,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  heroBadgeText: {
    color: colors.accent,
    fontSize: typography.caption,
    fontWeight: '800',
  },
  heroMeta: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  heroHighlightGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  heroHighlightCard: {
    flexGrow: 1,
    minWidth: 100,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  heroHighlightValue: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '900',
  },
  heroHighlightLabel: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  progressBlock: {
    gap: spacing.sm,
    padding: spacing.lg,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.66)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  progressTitle: {
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '900',
  },
  progressSubtitle: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  progressTrack: {
    height: 14,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: colors.gold,
  },
  progressCaption: {
    color: colors.textMuted,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  input: {
    minHeight: 52,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.gold,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    shadowColor: colors.gold,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  primaryButtonText: {
    color: colors.backgroundDeep,
    fontSize: typography.body,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  secondaryButtonText: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  badgeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  featuredBadgeCard: {
    flexGrow: 1,
    minWidth: 140,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  badgeCard: {
    flexGrow: 1,
    minWidth: 140,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  badgeIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeName: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
  },
  badgeMeta: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  badgeDescription: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  progressList: {
    gap: spacing.md,
  },
  playbookList: {
    gap: spacing.md,
  },
  playbookRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  playbookText: {
    flex: 1,
    gap: spacing.xs,
  },
  playbookTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
  },
  playbookBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  playbookValue: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  playbookValueMuted: {
    color: colors.textSoft,
  },
  playbookFootnote: {
    color: colors.textSoft,
    fontSize: typography.caption,
    fontWeight: '700',
    lineHeight: 18,
  },
  progressCard: {
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  progressText: {
    flex: 1,
    gap: spacing.xs,
  },
  progressCardTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
  },
  progressCardBody: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  progressValue: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  loading: {
    paddingVertical: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  environmentList: {
    gap: spacing.sm,
  },
  environmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  environmentLabel: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  environmentValue: {
    flex: 1,
    textAlign: 'right',
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
  },
  environmentNote: {
    color: colors.textSoft,
    fontSize: typography.body,
    lineHeight: 22,
  },
  previewCard: {
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.lg,
    gap: spacing.md,
  },
  previewCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  previewCardTitle: {
    flex: 1,
    color: colors.text,
    fontSize: typography.section,
    fontWeight: '900',
  },
  previewDismissButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  previewCardBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
  },
  contactList: {
    gap: spacing.sm,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  contactLabel: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  contactValue: {
    flex: 1,
    textAlign: 'right',
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.textSoft,
    fontSize: typography.body,
    lineHeight: 22,
  },
});
