import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamilies, radii, spacing, textStyles, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  heroCard: {
    backgroundColor: colors.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.07)',
    borderRadius: radii.xl,
    padding: spacing.xxl,
    gap: spacing.xl,
    shadowColor: colors.shadow,
    shadowOpacity: 0.26,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
    overflow: 'hidden',
  },
  heroGlow: {
    position: 'absolute',
    top: -64,
    right: -42,
    width: 236,
    height: 236,
    borderRadius: 118,
    backgroundColor: Platform.select({
      android: 'rgba(245, 200, 106, 0.10)',
      default: 'rgba(245, 200, 106, 0.06)',
    }),
    borderWidth: Platform.OS === 'android' ? 1 : 0,
    borderColor: 'rgba(245, 200, 106, 0.12)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.lg,
  },
  avatarWrap: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 14, 19, 0.82)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  avatarText: {
    color: colors.text,
    fontFamily: fontFamilies.display,
    fontSize: 24,
    lineHeight: 26,
  },
  heroBody: {
    flex: 1,
    gap: spacing.md,
  },
  heroTitleRow: {
    gap: spacing.md,
  },
  heroKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  heroKicker: {
    ...textStyles.labelCaps,
    color: colors.goldSoft,
  },
  heroMiniChip: {
    minHeight: 32,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroMiniChipText: {
    ...textStyles.caption,
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  heroName: {
    ...textStyles.title,
    color: colors.text,
    fontSize: 28,
    lineHeight: 34,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 140, 0.18)',
  },
  heroBadgeText: {
    ...textStyles.caption,
    color: colors.accent,
  },
  heroMeta: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 24,
  },
  heroHighlightGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  heroHighlightCard: {
    flexGrow: 1,
    minWidth: 100,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.70)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  heroHighlightValue: {
    ...textStyles.title,
    color: colors.text,
  },
  heroHighlightLabel: {
    ...textStyles.labelCaps,
    color: colors.textMuted,
    lineHeight: 18,
  },
  progressBlock: {
    gap: spacing.md,
    padding: spacing.xl,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.66)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  progressTitle: {
    ...textStyles.section,
    color: colors.text,
  },
  progressSubtitle: {
    ...textStyles.caption,
    color: colors.goldSoft,
  },
  progressTrack: {
    height: 14,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: colors.gold,
  },
  progressCaption: {
    ...textStyles.caption,
    color: colors.textMuted,
    lineHeight: 18,
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  surfaceSwitcher: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  surfaceSwitcherButton: {
    minWidth: 136,
    flexGrow: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  surfaceSwitcherButtonActive: {
    borderColor: 'rgba(245, 200, 106, 0.24)',
    backgroundColor: 'rgba(245, 200, 106, 0.10)',
  },
  surfaceSwitcherButtonLabel: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  surfaceSwitcherButtonLabelActive: {
    color: colors.goldSoft,
  },
  surfaceSwitcherButtonBody: {
    ...textStyles.caption,
    color: colors.textMuted,
    lineHeight: 18,
  },
  surfaceSwitcherButtonBodyActive: {
    color: colors.textSoft,
  },
  fieldGroup: {
    gap: spacing.md,
  },
  fieldLabel: {
    ...textStyles.labelCaps,
    color: colors.textSoft,
  },
  fieldHint: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  accountSnapshotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  accountSnapshotCard: {
    minWidth: 136,
    flexGrow: 1,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.7)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  accountSnapshotValue: {
    ...textStyles.title,
    color: colors.text,
  },
  accountSnapshotLabel: {
    ...textStyles.labelCaps,
    color: colors.textMuted,
  },
  accountSnapshotBody: {
    ...textStyles.caption,
    color: colors.textMuted,
    lineHeight: 18,
  },
  input: {
    minHeight: 54,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    color: colors.text,
    ...textStyles.bodyStrong,
    paddingVertical: spacing.md,
  },
  primaryButton: {
    minHeight: 52,
    minWidth: 152,
    flexGrow: 1,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.xl,
    backgroundColor: colors.gold,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    shadowColor: colors.gold,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
  },
  primaryButtonText: {
    ...textStyles.button,
    color: colors.backgroundDeep,
    letterSpacing: 0.2,
  },
  secondaryButton: {
    minHeight: 52,
    minWidth: 152,
    flexGrow: 1,
    borderRadius: radii.lg,
    paddingHorizontal: spacing.xl,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  secondaryButtonText: {
    ...textStyles.button,
    color: colors.text,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  badgeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  featuredBadgeCard: {
    flexGrow: 1,
    minWidth: 148,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.22)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    gap: spacing.sm,
    alignItems: 'center',
    shadowColor: colors.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
    overflow: 'hidden',
  },
  badgeCard: {
    flexGrow: 1,
    minWidth: 148,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    gap: spacing.sm,
    alignItems: 'center',
    shadowColor: colors.shadow,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
    overflow: 'hidden',
  },
  badgeIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.32,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  badgeName: {
    ...textStyles.bodyStrong,
    color: colors.text,
    textAlign: 'center',
  },
  badgeMeta: {
    ...textStyles.caption,
    color: colors.goldSoft,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: '800',
  },
  badgeTierPill: {
    marginTop: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(245, 200, 106, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.32)',
  },
  badgeTierPillText: {
    ...textStyles.caption,
    color: colors.goldSoft,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontWeight: '900',
  },
  badgeDescription: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
    textAlign: 'center',
  },
  progressList: {
    gap: spacing.md,
  },
  playbookList: {
    gap: spacing.md,
  },
  playbookRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  playbookText: {
    flex: 1,
    gap: spacing.xs,
  },
  playbookTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  playbookBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 20,
  },
  playbookValue: {
    color: colors.goldSoft,
    fontSize: typography.caption,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  playbookValueMuted: {
    color: colors.textSoft,
  },
  playbookFootnote: {
    ...textStyles.caption,
    color: colors.textSoft,
    lineHeight: 18,
  },
  progressCard: {
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.xl,
    gap: spacing.md,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  progressText: {
    flex: 1,
    gap: spacing.xs,
  },
  progressCardTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
  },
  progressCardBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  progressValue: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  loading: {
    paddingVertical: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  environmentList: {
    gap: spacing.sm,
  },
  environmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  environmentLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  environmentValue: {
    flex: 1,
    textAlign: 'right',
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
    lineHeight: 22,
  },
  environmentNote: {
    color: colors.textSoft,
    fontSize: typography.body,
    lineHeight: 22,
  },
  previewCard: {
    borderRadius: radii.lg,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: spacing.xl,
    gap: spacing.lg,
  },
  previewCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  previewCardTitle: {
    ...textStyles.section,
    flex: 1,
    color: colors.text,
    lineHeight: 26,
  },
  previewDismissButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  previewCardBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 24,
  },
  contactList: {
    gap: spacing.sm,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  contactLabel: {
    ...textStyles.caption,
    color: colors.textSoft,
  },
  contactValue: {
    flex: 1,
    textAlign: 'right',
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
    lineHeight: 22,
  },
  emptyText: {
    color: colors.textSoft,
    fontSize: typography.body,
    lineHeight: 24,
  },
  displayNameInput: {
    ...textStyles.body,
    color: colors.text,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    borderRadius: radii.md,
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    minHeight: 48,
  },
});
