import { GamificationBadgeDefinition } from '../../types/storefront';

export const CANOPYTROVE_BADGES: GamificationBadgeDefinition[] = [
  {
    id: 'reviewer_1',
    name: 'First Review',
    description: 'Write your first review',
    icon: 'star-outline',
    color: '#00F58C',
    category: 'review',
    points: 50,
    requirement: 1,
    hidden: false,
    tier: 'bronze',
  },
  {
    id: 'reviewer_5',
    name: 'Active Reviewer',
    description: 'Write 5 reviews',
    icon: 'star-half-outline',
    color: '#00F58C',
    category: 'review',
    points: 100,
    requirement: 5,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'reviewer_25',
    name: 'Prolific Reviewer',
    description: 'Write 25 reviews',
    icon: 'star',
    color: '#00F58C',
    category: 'review',
    points: 300,
    requirement: 25,
    hidden: false,
    tier: 'gold',
  },
  {
    id: 'reviewer_100',
    name: 'Review Legend',
    description: 'Write 100 reviews',
    icon: 'trophy',
    color: '#FFD166',
    category: 'review',
    points: 1000,
    requirement: 100,
    hidden: false,
    tier: 'platinum',
  },
  {
    id: 'five_star_reviewer',
    name: 'High Standards',
    description: 'Leave 10 five-star reviews',
    icon: 'star',
    color: '#FFD166',
    category: 'review',
    points: 150,
    requirement: 10,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'detailed_reviewer',
    name: 'Wordsmith',
    description: 'Write 10 detailed reviews (100+ characters)',
    icon: 'document-text-outline',
    color: '#40D6FF',
    category: 'review',
    points: 200,
    requirement: 10,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'helpful_reviewer',
    name: 'Helpful Voice',
    description: 'Receive 25 helpful votes on your reviews',
    icon: 'thumbs-up-outline',
    color: '#7CFFB6',
    category: 'review',
    points: 250,
    requirement: 25,
    hidden: false,
    tier: 'gold',
  },
  {
    id: 'photographer_1',
    name: 'Snap Happy',
    description: 'Upload your first photo',
    icon: 'camera-outline',
    color: '#8C3BFF',
    category: 'photo',
    points: 50,
    requirement: 1,
    hidden: false,
    tier: 'bronze',
  },
  {
    id: 'photographer_10',
    name: 'Shutterbug',
    description: 'Upload 10 photos',
    icon: 'camera',
    color: '#8C3BFF',
    category: 'photo',
    points: 150,
    requirement: 10,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'photographer_50',
    name: 'Photojournalist',
    description: 'Upload 50 photos',
    icon: 'images-outline',
    color: '#8C3BFF',
    category: 'photo',
    points: 500,
    requirement: 50,
    hidden: false,
    tier: 'gold',
  },
  {
    id: 'visitor_1',
    name: 'First Stop',
    description: 'Visit your first dispensary',
    icon: 'location-outline',
    color: '#00F58C',
    category: 'explorer',
    points: 25,
    requirement: 1,
    hidden: false,
    tier: 'bronze',
  },
  {
    id: 'visitor_10',
    name: 'Explorer',
    description: 'Visit 10 dispensaries',
    icon: 'map-outline',
    color: '#40D6FF',
    category: 'explorer',
    points: 150,
    requirement: 10,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'local_explorer',
    name: 'Local Expert',
    description: 'Visit 25 dispensaries',
    icon: 'compass-outline',
    color: '#40D6FF',
    category: 'explorer',
    points: 300,
    requirement: 25,
    hidden: false,
    tier: 'gold',
  },
  {
    id: 'dispensary_master',
    name: 'Dispensary Master',
    description: 'Visit 100 dispensaries',
    icon: 'earth-outline',
    color: '#7CFFB6',
    category: 'explorer',
    points: 1000,
    requirement: 100,
    hidden: false,
    tier: 'platinum',
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day activity streak',
    icon: 'flame-outline',
    color: '#8C3BFF',
    category: 'milestone',
    points: 100,
    requirement: 7,
    hidden: false,
    tier: 'bronze',
  },
  {
    id: 'streak_30',
    name: 'Monthly Grind',
    description: 'Maintain a 30-day activity streak',
    icon: 'flame',
    color: '#8C3BFF',
    category: 'milestone',
    points: 500,
    requirement: 30,
    hidden: false,
    tier: 'gold',
  },
  {
    id: 'member_30',
    name: 'Loyal Member',
    description: 'Be a member for 30 days',
    icon: 'ribbon-outline',
    color: '#7CFFB6',
    category: 'milestone',
    points: 100,
    requirement: 30,
    hidden: false,
    tier: 'bronze',
  },
  {
    id: 'member_365',
    name: 'Year One',
    description: 'Be a member for 1 year',
    icon: 'ribbon',
    color: '#FFD166',
    category: 'milestone',
    points: 1000,
    requirement: 365,
    hidden: false,
    tier: 'platinum',
  },
  {
    id: 'helpful_25',
    name: 'Community Helper',
    description: 'Receive 25 helpful votes',
    icon: 'people-outline',
    color: '#7CFFB6',
    category: 'social',
    points: 200,
    requirement: 25,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'followed_10',
    name: 'Rising Star',
    description: 'Gain 10 followers',
    icon: 'person-add-outline',
    color: '#7CFFB6',
    category: 'social',
    points: 200,
    requirement: 10,
    hidden: false,
    tier: 'silver',
  },
  {
    id: 'ambassador',
    name: 'Ambassador',
    description: 'Invite 5 friends',
    icon: 'share-social-outline',
    color: '#40D6FF',
    category: 'community',
    points: 300,
    requirement: 5,
    hidden: false,
    tier: 'gold',
  },
  {
    id: 'early_adopter',
    name: 'Early Adopter',
    description: 'Joined during the early access period',
    icon: 'rocket-outline',
    color: '#FFD166',
    category: 'special',
    points: 500,
    requirement: 0,
    hidden: false,
    tier: 'diamond',
  },
  {
    id: 'verified_user',
    name: 'Verified',
    description: 'Verified CanopyTrove member',
    icon: 'shield-checkmark-outline',
    color: '#40D6FF',
    category: 'special',
    points: 100,
    requirement: 0,
    hidden: false,
    tier: 'silver',
  },
];
