import { StyleSheet } from 'react-native';
import { colors, fontFamilies, radii, spacing, textStyles, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  ambientWrap: {
    ...StyleSheet.absoluteFillObject,
  },
  ambientOrb: {
    position: 'absolute',
    borderRadius: radii.pill,
  },
  ambientOrbPrimary: {
    top: -80,
    right: -46,
    width: 240,
    height: 240,
    backgroundColor: 'rgba(0, 245, 140, 0.08)',
    shadowColor: colors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 42,
    shadowOffset: { width: 0, height: 16 },
  },
  ambientOrbWarm: {
    bottom: 96,
    left: -72,
    width: 180,
    height: 180,
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
  },
  ambientBeam: {
    position: 'absolute',
    top: 90,
    left: spacing.lg,
    right: spacing.lg,
    height: 240,
    borderRadius: 40,
    opacity: 0.34,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xxl,
    justifyContent: 'center',
  },
  shell: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.14)',
    backgroundColor: 'rgba(8, 14, 19, 0.78)',
    padding: spacing.xl,
    gap: spacing.xl,
    shadowColor: colors.shadow,
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    overflow: 'hidden',
  },
  header: {
    gap: spacing.lg,
    alignItems: 'center',
  },
  logoRow: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 224,
  },
  logoPulse: {
    position: 'absolute',
    width: 248,
    height: 248,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
  },
  logoCore: {
    width: 248,
    height: 248,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandLockup: {
    alignItems: 'center',
    gap: spacing.sm,
    width: '100%',
  },
  kickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
  },
  liveBadgeText: {
    ...textStyles.labelCaps,
    color: colors.goldSoft,
    letterSpacing: 0.4,
  },
  eyebrow: {
    ...textStyles.labelCaps,
    color: colors.goldSoft,
    letterSpacing: 1,
  },
  title: {
    ...textStyles.display,
    color: colors.text,
    fontSize: typography.display,
    lineHeight: 36,
    textAlign: 'center',
  },
  subtitle: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
    textAlign: 'center',
  },
  statusChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  statusChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.76)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  statusChipText: {
    ...textStyles.caption,
    fontFamily: fontFamilies.bodyBold,
    color: colors.accent,
  },
  progressRail: {
    marginTop: spacing.sm,
    height: 8,
    borderRadius: radii.pill,
    overflow: 'hidden',
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.border,
    width: '100%',
  },
  progressSweep: {
    position: 'absolute',
    top: -10,
    bottom: -10,
    width: 110,
    backgroundColor: 'rgba(0, 245, 140, 0.32)',
  },
  bootNoteCard: {
    width: '100%',
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(245, 200, 106, 0.18)',
    backgroundColor: 'rgba(245, 200, 106, 0.08)',
    padding: spacing.lg,
    gap: spacing.xs,
  },
  bootNoteTitle: {
    ...textStyles.bodyStrong,
    color: colors.text,
    textAlign: 'center',
  },
  bootNoteBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
    textAlign: 'center',
  },
  heroCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(10, 17, 23, 0.96)',
    padding: spacing.xl,
    gap: spacing.md,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  heroEyebrow: {
    ...textStyles.labelCaps,
    color: colors.goldSoft,
    letterSpacing: 0.5,
  },
  heroBadge: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(8, 14, 19, 0.72)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  heroBadgeText: {
    ...textStyles.caption,
    fontFamily: fontFamilies.bodyBold,
    color: colors.accent,
  },
  heroMapWrap: {
    borderRadius: radii.md,
    overflow: 'hidden',
  },
  heroMap: {
    height: 152,
    borderWidth: 1,
    borderColor: colors.border,
  },
  heroTitle: {
    ...textStyles.section,
    color: colors.text,
    fontSize: typography.section,
  },
  heroBody: {
    ...textStyles.body,
    color: colors.textMuted,
    lineHeight: 22,
  },
  heroLineShort: {
    width: '42%',
    height: 10,
  },
  heroLineLong: {
    width: '78%',
    height: 10,
  },
  heroChipRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  heroChip: {
    width: 74,
    height: 28,
  },
  heroChipWide: {
    width: 110,
    height: 28,
  },
  cardStack: {
    gap: spacing.lg,
  },
  card: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    overflow: 'hidden',
  },
  cardMap: {
    height: 110,
  },
  cardBody: {
    padding: spacing.lg,
    gap: spacing.sm,
  },
  cardLineStrong: {
    width: '58%',
    height: 10,
  },
  cardLineSoft: {
    width: '74%',
    height: 10,
  },
  cardChipRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  cardChip: {
    width: 82,
    height: 28,
  },
});
